/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minicontador;

import clases.cl_conectar;
import clases.cl_empresas;
import clases.cl_entidad;
import clases.cl_usuario;
import clases.cl_varios;
import clases_varios.cl_PeticionPost;
import clases_varios.cl_json_entidad;
import java.awt.Desktop;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import models.m_empresas;
import objects.o_combobox;
import org.json.simple.parser.ParseException;
import vistas.frm_ver_compras;
import vistas.frm_ver_diario;
import vistas.frm_ver_empresas;
import vistas.frm_ver_plan_contable;
import vistas.frm_ver_ventas;

/**
 *
 * @author CALIDAD
 */
public class frm_menu extends javax.swing.JFrame {

    cl_varios c_varios = new cl_varios();
    cl_conectar c_conectar = new cl_conectar();

    public static cl_usuario c_usuario = new cl_usuario();
    public static cl_empresas c_empresa = new cl_empresas();
    public static cl_entidad c_entidad = new cl_entidad();

    /**
     * Creates new form frm_menu
     */
    public frm_menu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        if (c_conectar.conectar()) {
            autoconectar();
            cargar_login();
        } else {
            JOptionPane.showMessageDialog(null, "ERROR!! , NO ES POSIBLE CONECTAR A LA BASE DE DATOS");
            System.exit(0);
        }
    }

    private void cargar_login() {
        frm_login.setSize(318, 431);
        frm_login.setModal(true);
        frm_login.setLocationRelativeTo(null);
        frm_login.setVisible(true);
    }

    private void cargar_registro() {
        frm_registrar.setSize(473, 578);
        frm_registrar.setModal(true);
        frm_registrar.setLocationRelativeTo(null);
        frm_registrar.setVisible(true);
    }

    public void validar_conexion() {
        if (c_conectar.verificar_conexion()) {
            c_conectar.conectar();
        } else {
            JOptionPane.showMessageDialog(null, "LO SENTIMOS NO TIENE CONECCION A INTERNET, se cerrara el programa");
            System.exit(0);
        }
    }

    private void autoconectar() {
        try {
            Timer timer = new Timer(35000, new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    c_usuario.autoconectar();
                }
            });
            timer.start();
            timer.setRepeats(true);
        } catch (Exception e) {
            System.out.println("Error grave " + e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frm_login = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_email_login = new javax.swing.JTextField();
        txt_contra_login = new javax.swing.JPasswordField();
        cbx_empresas = new javax.swing.JComboBox<>();
        btn_logear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        frm_registrar = new javax.swing.JDialog();
        btn_add_reg = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btn_salir_reg = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txt_ruc_reg = new javax.swing.JTextField();
        txt_razon_reg = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_nombres_reg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_celular_reg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_email_reg = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_pass_reg = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        txt_valida_pass = new javax.swing.JPasswordField();
        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton8 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        lbl_ruc = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_razon_social = new javax.swing.JLabel();

        frm_login.setDefaultCloseOperation(0);
        frm_login.setTitle("Acceder al Sistema");
        frm_login.setAlwaysOnTop(true);
        frm_login.setResizable(false);

        jLabel2.setText("Ingrese Email:");

        jLabel4.setText("Ingrese Contraseña:");

        jLabel6.setText("Seleccionar Empresa:");

        txt_email_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_email_loginKeyPressed(evt);
            }
        });

        txt_contra_login.setEnabled(false);
        txt_contra_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contra_loginKeyPressed(evt);
            }
        });

        cbx_empresas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACCEDA PRIMERO" }));
        cbx_empresas.setEnabled(false);
        cbx_empresas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_empresasKeyPressed(evt);
            }
        });

        btn_logear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/accept.png"))); // NOI18N
        btn_logear.setText("Ingresar");
        btn_logear.setEnabled(false);
        btn_logear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logearActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/application_add.png"))); // NOI18N
        jLabel7.setText("Crear Cuenta..");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setEnabled(false);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/164426.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cross.png"))); // NOI18N
        jLabel15.setText("Salir");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frm_loginLayout = new javax.swing.GroupLayout(frm_login.getContentPane());
        frm_login.getContentPane().setLayout(frm_loginLayout);
        frm_loginLayout.setHorizontalGroup(
            frm_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frm_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_empresas, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_loginLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(txt_contra_login)
                    .addComponent(txt_email_login)
                    .addGroup(frm_loginLayout.createSequentialGroup()
                        .addGroup(frm_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(frm_loginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btn_logear, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addGroup(frm_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        frm_loginLayout.setVerticalGroup(
            frm_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email_login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_contra_login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_empresas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_logear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frm_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        btn_add_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/accept.png"))); // NOI18N
        btn_add_reg.setText("Grabar");
        btn_add_reg.setEnabled(false);
        btn_add_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_regActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CREAR CUENTA");

        btn_salir_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cross.png"))); // NOI18N
        btn_salir_reg.setText("Cancelar");
        btn_salir_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_regActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empresa"));

        jLabel16.setText("RUC:");

        txt_ruc_reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ruc_regKeyPressed(evt);
            }
        });

        txt_razon_reg.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_razon_reg)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ruc_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_ruc_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_razon_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Usuario"));

        jLabel9.setText("Apellidos y Nombres:");

        txt_nombres_reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombres_regKeyPressed(evt);
            }
        });

        jLabel11.setText("Nro de Celular:");

        txt_celular_reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_celular_regKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_celular_regKeyPressed(evt);
            }
        });

        jLabel10.setText("Correo Electronico:");

        txt_email_reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_email_regKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_email_regKeyReleased(evt);
            }
        });

        jLabel12.setText("Contraseña:");

        txt_pass_reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pass_regKeyPressed(evt);
            }
        });

        jLabel13.setText("Repetir Contraseña:");

        txt_valida_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_valida_passKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombres_reg)
                    .addComponent(txt_email_reg)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_pass_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(txt_valida_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(txt_celular_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombres_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_celular_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_valida_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frm_registrarLayout = new javax.swing.GroupLayout(frm_registrar.getContentPane());
        frm_registrar.getContentPane().setLayout(frm_registrarLayout);
        frm_registrarLayout.setHorizontalGroup(
            frm_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_registrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frm_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frm_registrarLayout.createSequentialGroup()
                        .addComponent(btn_salir_reg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(btn_add_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        frm_registrarLayout.setVerticalGroup(
            frm_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_registrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frm_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema minicontable -- Luna Systems Peru");

        jToolBar1.setFloatable(false);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/86-512.png"))); // NOI18N
        jButton3.setText("Mis Datos");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/company_building-512.png"))); // NOI18N
        jButton1.setText("Mis Empresas");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator3);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Sales-by-payment-method-icon.png"))); // NOI18N
        jButton5.setText("Ventas");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/shopping2-02-512.png"))); // NOI18N
        jButton6.setText("Compras");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/P-1-26-512.png"))); // NOI18N
        jButton2.setText("Mov. Diario");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/customer-testimonials-512.png"))); // NOI18N
        jButton4.setText("Clientes / Proveedores");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator4);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/shopping-21-512.png"))); // NOI18N
        jButton7.setText("Plan Contable");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);
        jToolBar1.add(jSeparator5);

        jButton8.setText("Abrir Carpeta L.E.");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        jToolBar2.setFloatable(false);

        jLabel1.setText("RUC: ");
        jToolBar2.add(jLabel1);

        lbl_ruc.setText("10469932091");
        jToolBar2.add(lbl_ruc);
        jToolBar2.add(jSeparator1);

        jLabel5.setText("   ");
        jToolBar2.add(jLabel5);

        jLabel3.setText("Razon Social: ");
        jToolBar2.add(jLabel3);

        lbl_razon_social.setText("OYANGUREN GIRON LUIS ENRIQUE");
        jToolBar2.add(lbl_razon_social);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1)
                .addGap(0, 0, 0)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Frame f = JOptionPane.getRootFrame();
        frm_mis_datos dialog = new frm_mis_datos(f, true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frm_ver_empresas formulario = new frm_ver_empresas();
        c_varios.llamar_ventana(formulario);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frm_ver_ventas formulario = new frm_ver_ventas();
        c_varios.llamar_ventana_ancha(formulario);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        frm_ver_compras formulario = new frm_ver_compras();
        c_varios.llamar_ventana_ancha(formulario);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_salir_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_regActionPerformed
        frm_registrar.dispose();
    }//GEN-LAST:event_btn_salir_regActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        cargar_registro();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void btn_add_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_regActionPerformed
        c_conectar.conectar();

        c_usuario.setNombres(txt_nombres_reg.getText().trim().toUpperCase());
        c_usuario.setCelular(txt_celular_reg.getText());
        c_usuario.setEmail(txt_email_reg.getText());
        boolean existe_email = c_usuario.validar_email();
        if (!existe_email) {
            String password = String.valueOf(txt_pass_reg.getPassword());
            String valida_pass = String.valueOf(txt_valida_pass.getPassword());
            if (password.equals(valida_pass)) {
                c_usuario.setPassword(password);
            } else {
                JOptionPane.showMessageDialog(null, "CONTRASEÑA NO COINCIDEN");
                txt_pass_reg.requestFocus();
            }

            c_usuario.obtener_id();

            boolean registrado = c_usuario.insertar();

            if (registrado) {
                c_entidad.setId_usuario(c_usuario.getId_usuario());
                c_entidad.obtener_id();
                boolean registrar_entidad = c_entidad.insertar();

                if (registrar_entidad) {
                    c_empresa.setId_usuario(c_usuario.getId_usuario());
                    c_empresa.setId_entidad(c_entidad.getId_entidad());
                    c_empresa.obtener_id();

                    if (c_empresa.insertar()) {
                        cl_entidad c_entidad_0 = new cl_entidad();
                        c_entidad_0.setDocumento("0");
                        c_entidad_0.setDireccion("-");
                        c_entidad_0.setId_usuario(c_usuario.getId_usuario());
                        c_entidad_0.setNombre("EMPRESA NO IDENTIFICADA");
                        c_entidad_0.setId_entidad(0);
                        c_entidad_0.insertar();

                        cl_PeticionPost c_peticion = new cl_PeticionPost();

                        String mensaje = "USUARIO CREADO EN MINICONTADOR!!. Para acceder su email es: " + c_usuario.getEmail() + " y su contraseña es: " + c_usuario.getPassword() + ". GRACIAS. Atte. LunaSystemsPeru";
                        c_peticion.excutePost(mensaje, c_usuario.getCelular());
                        //cerrar formulario registro
                        frm_registrar.dispose();
                    }
                }
                //enviar sms con acceso 

            }
        } else {
            JOptionPane.showMessageDialog(frm_registrar, "EL EMAIL YA ESTA REGISTRADO, POR FAVOR COMUNIQUESE CON NOSOTROS.");
            txt_email_reg.requestFocus();
        }

    }//GEN-LAST:event_btn_add_regActionPerformed

    private void txt_nombres_regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombres_regKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_nombres_reg.getText().length() > 10) {
                txt_celular_reg.setEnabled(true);
                txt_celular_reg.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_nombres_regKeyPressed

    private void txt_celular_regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_celular_regKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_celular_reg.getText().length() == 9) {
                txt_email_reg.setEnabled(true);
                txt_email_reg.requestFocus();
            } else {
                JOptionPane.showMessageDialog(frm_registrar, "Ingrese un numero de celular");
            }
        }
    }//GEN-LAST:event_txt_celular_regKeyPressed

    private void txt_email_regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_email_regKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_email_reg.getText().length() > 9) {
                txt_pass_reg.setEnabled(true);
                txt_pass_reg.requestFocus();
            } else {
                JOptionPane.showMessageDialog(frm_registrar, "Ingrese un correo valido");
                txt_email_reg.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_email_regKeyPressed

    private void txt_pass_regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pass_regKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_pass_reg.getText().length() > 3) {
                txt_valida_pass.setEnabled(true);
                txt_valida_pass.requestFocus();
            } else {
                JOptionPane.showMessageDialog(frm_registrar, "Ingrese una contraseña mayor a 3 digitos");
                txt_pass_reg.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_pass_regKeyPressed

    private void txt_valida_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valida_passKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_valida_pass.getText().length() > 3) {
                txt_ruc_reg.setEnabled(true);
                txt_ruc_reg.requestFocus();
            } else {
                JOptionPane.showMessageDialog(frm_registrar, "Ingrese una contraseña mayor a 3 digitos");
                txt_valida_pass.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_valida_passKeyPressed

    private void txt_celular_regKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_celular_regKeyTyped
        c_varios.solo_numeros(evt);
        c_varios.limitar_caracteres(evt, txt_celular_reg, 9);
    }//GEN-LAST:event_txt_celular_regKeyTyped

    private void txt_email_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_email_loginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_email_login.getText().length() > 3) {
                //validar_conexion();
                c_usuario.setEmail(txt_email_login.getText().trim());
                boolean existe_email = c_usuario.validar_email();
                if (existe_email) {
                    c_usuario.obtener_datos();
                    txt_email_login.setEnabled(false);
                    txt_contra_login.setEnabled(true);
                    txt_contra_login.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(frm_login, "ESTE CORREO NO ESTA REGISTRADO, POR FAVOR HAGA CLIC EN CREAR CUENTA, SI DESEA ALGUNA.");
                    txt_email_login.selectAll();
                    txt_email_login.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(frm_login, "Ingrese un correo correcto");
                txt_email_login.selectAll();
                txt_email_login.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_email_loginKeyPressed

    private void txt_email_regKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_email_regKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_regKeyReleased

    private void txt_contra_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contra_loginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_contra_login.getText().length() > 3) {
                String pass = String.valueOf(txt_contra_login.getPassword());
                if (pass.equals(c_usuario.getPassword())) {
                    //cargar empresas
                    m_empresas m_empresas = new m_empresas();
                    m_empresas.listar_empresas(cbx_empresas);
                    cbx_empresas.setEnabled(true);
                    cbx_empresas.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(frm_login, "Contraseña Incorrecta..");
                    txt_contra_login.selectAll();
                    txt_contra_login.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(frm_login, "Ingrese su contraseña");
                txt_contra_login.selectAll();
                txt_contra_login.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_contra_loginKeyPressed

    private void txt_ruc_regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ruc_regKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_ruc_reg.getText().length() == 11) {
                String ruc = txt_ruc_reg.getText().trim();
                try {
                    String json_entidad = cl_json_entidad.getJSONRUC(ruc);
                    String[] datos_entidad = cl_json_entidad.showJSONRUC(json_entidad);
                    txt_razon_reg.setText(datos_entidad[0].trim());
                    c_entidad.setDocumento(ruc);
                    c_entidad.setDireccion(datos_entidad[1].trim());
                    c_entidad.setNombre(datos_entidad[0].trim());
                    btn_add_reg.setEnabled(true);
                    btn_add_reg.requestFocus();
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
                }
            } else {
                JOptionPane.showMessageDialog(frm_login, "Ingrese un numero correcto, 11 digitos");
                txt_contra_login.selectAll();
                txt_contra_login.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_ruc_regKeyPressed

    private void cbx_empresasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_empresasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_logear.setEnabled(true);
            btn_logear.requestFocus();
        }
    }//GEN-LAST:event_cbx_empresasKeyPressed

    private void btn_logearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logearActionPerformed
        o_combobox c_cbx_empresas = (o_combobox) cbx_empresas.getSelectedItem();
        int id_empresa = c_cbx_empresas.getId();
        c_empresa.setId_empresa(id_empresa);
        c_empresa.setId_usuario(c_usuario.getId_usuario());
        c_empresa.obtener_datos();

        c_entidad.setId_usuario(c_empresa.getId_usuario());
        c_entidad.setId_entidad(c_empresa.getId_entidad());
        c_entidad.obtener_datos();

        lbl_ruc.setText(c_entidad.getDocumento());
        lbl_razon_social.setText(c_entidad.getNombre());
        frm_login.dispose();
    }//GEN-LAST:event_btn_logearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frm_ver_diario formulario = new frm_ver_diario();
        c_varios.llamar_ventana_ancha(formulario);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        frm_ver_plan_contable formulario = new frm_ver_plan_contable();
        c_varios.llamar_ventana(formulario);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            File dir = new File(".");
            Desktop.getDesktop().open(new File(dir.getCanonicalPath() + File.separator + "libros_electronicos" + File.separator + c_entidad.getDocumento()));
        } catch (IOException ex) {
            System.out.println(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_reg;
    private javax.swing.JButton btn_logear;
    private javax.swing.JButton btn_salir_reg;
    private javax.swing.JComboBox<String> cbx_empresas;
    private javax.swing.JDialog frm_login;
    private javax.swing.JDialog frm_registrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lbl_razon_social;
    private javax.swing.JLabel lbl_ruc;
    private javax.swing.JTextField txt_celular_reg;
    private javax.swing.JPasswordField txt_contra_login;
    private javax.swing.JTextField txt_email_login;
    private javax.swing.JTextField txt_email_reg;
    private javax.swing.JTextField txt_nombres_reg;
    private javax.swing.JPasswordField txt_pass_reg;
    private javax.swing.JTextField txt_razon_reg;
    private javax.swing.JTextField txt_ruc_reg;
    private javax.swing.JPasswordField txt_valida_pass;
    // End of variables declaration//GEN-END:variables
}
