-- MySQL Script generated by MySQL Workbench
-- Wed Oct  9 10:12:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema minicontable
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT NOT NULL,
  `nombres` VARCHAR(245) NULL,
  `email` VARCHAR(245) NULL,
  `fecha_registro` DATETIME NULL,
  `password` VARCHAR(15) NULL,
  `celular` VARCHAR(9) NULL,
  `estado` CHAR(1) NULL,
  `ultimo_ingreso` DATETIME NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entidad` (
  `id_entidad` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `documento` VARCHAR(11) NULL,
  `nombre` VARCHAR(245) NULL,
  `direccion` VARCHAR(245) NULL,
  PRIMARY KEY (`id_entidad`, `id_usuario`),
  CONSTRAINT `fk_entidad_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_entidad_usuarios1_idx` ON `entidad` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresas` (
  `id_empresa` INT NOT NULL,
  `id_entidad` INT NOT NULL,
  `estado` CHAR(1) NULL,
  `fecha_registro` DATE NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_empresa`),
  CONSTRAINT `fk_empresas_entidad1`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `entidad` (`id_entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_empresas_entidad1_idx` ON `empresas` (`id_entidad` ASC);

CREATE INDEX `fk_empresas_usuarios1_idx` ON `empresas` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `documentos_sunat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `documentos_sunat` (
  `id_tido` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `abreviatura` VARCHAR(3) NULL,
  `cod_sunat` VARCHAR(2) NULL,
  PRIMARY KEY (`id_tido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moneda` (
  `id_moneda` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `abreviatura` VARCHAR(3) NULL,
  PRIMARY KEY (`id_moneda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas` (
  `id_ventas` INT NOT NULL,
  `periodo` INT(6) NOT NULL,
  `id_empresa` INT NOT NULL,
  `fecha_emision` DATE NULL,
  `id_tido` INT NOT NULL,
  `serie` VARCHAR(12) NULL,
  `numero` INT(12) NULL,
  `id_entidad` INT NOT NULL,
  `id_moneda` INT NOT NULL,
  `tc` DOUBLE(5,3) NULL,
  `subtotal` DOUBLE(8,2) NULL,
  `igv` DOUBLE(8,2) NULL,
  `total` DOUBLE(8,2) NULL,
  `tipo_venta` INT(1) NULL,
  `estado` CHAR(1) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_ventas`, `periodo`, `id_empresa`),
  CONSTRAINT `fk_ventas_empresas1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_entidad1`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `entidad` (`id_entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_documentos_sunat1`
    FOREIGN KEY (`id_tido`)
    REFERENCES `documentos_sunat` (`id_tido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_moneda1`
    FOREIGN KEY (`id_moneda`)
    REFERENCES `moneda` (`id_moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ventas_empresas1_idx` ON `ventas` (`id_empresa` ASC);

CREATE INDEX `fk_ventas_entidad1_idx` ON `ventas` (`id_entidad` ASC);

CREATE INDEX `fk_ventas_documentos_sunat1_idx` ON `ventas` (`id_tido` ASC);

CREATE INDEX `fk_ventas_moneda1_idx` ON `ventas` (`id_moneda` ASC);

CREATE INDEX `fk_ventas_usuarios1_idx` ON `ventas` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras` (
  `id_compras` INT NOT NULL,
  `periodo` INT(6) NOT NULL,
  `id_empresa` INT NOT NULL,
  `fecha_emision` DATE NULL,
  `fecha_vcto` DATE NULL,
  `id_tido` INT NOT NULL,
  `serie` VARCHAR(12) NULL,
  `numero` VARCHAR(12) NULL,
  `id_entidad` INT NOT NULL,
  `id_moneda` INT NOT NULL,
  `tc` DOUBLE(5,3) NULL,
  `subtotal` DOUBLE(8,2) NULL,
  `igv` DOUBLE(8,2) NULL,
  `total` DOUBLE(8,2) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_compras`, `periodo`, `id_empresa`),
  CONSTRAINT `fk_compras_empresas1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_documentos_sunat1`
    FOREIGN KEY (`id_tido`)
    REFERENCES `documentos_sunat` (`id_tido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_entidad1`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `entidad` (`id_entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_moneda1`
    FOREIGN KEY (`id_moneda`)
    REFERENCES `moneda` (`id_moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_compras_empresas1_idx` ON `compras` (`id_empresa` ASC);

CREATE INDEX `fk_compras_documentos_sunat1_idx` ON `compras` (`id_tido` ASC);

CREATE INDEX `fk_compras_entidad1_idx` ON `compras` (`id_entidad` ASC);

CREATE INDEX `fk_compras_moneda1_idx` ON `compras` (`id_moneda` ASC);

CREATE INDEX `fk_compras_usuarios1_idx` ON `compras` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `recordatorio_sunat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recordatorio_sunat` (
  `numero` INT(1) NOT NULL,
  `anio` INT(4) NOT NULL,
  `mes` INT(2) NOT NULL,
  `fecha_vcto` DATE NULL,
  PRIMARY KEY (`anio`, `numero`, `mes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuentas_contables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentas_contables` (
  `id_cuenta_contable` VARCHAR(6) NOT NULL,
  `nombre` VARCHAR(245) NULL,
  PRIMARY KEY (`id_cuenta_contable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libro_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libro_diario` (
  `periodo` VARCHAR(6) NOT NULL,
  `subdiario` INT NOT NULL,
  `id_diario` INT NOT NULL,
  `id_empresa` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `tipo_asiento` VARCHAR(6) NULL,
  `id_cuenta_contable` VARCHAR(6) NOT NULL,
  `id_centro_costo` VARCHAR(8) NULL,
  `id_moneda` INT NOT NULL,
  `doc_entidad` VARCHAR(45) NULL,
  `id_tido` INT NOT NULL,
  `serie_doc` VARCHAR(45) NULL,
  `numero_doc` VARCHAR(45) NULL,
  `fecha_cble` DATE NULL,
  `fecha_vcto` DATE NULL,
  `glosa` VARCHAR(45) NULL,
  `debe` DOUBLE(8,2) NULL,
  `haber` DOUBLE(8,2) NULL,
  `codigo_libro` VARCHAR(45) NULL,
  `estado_operacion` VARCHAR(1) NULL,
  PRIMARY KEY (`periodo`, `subdiario`, `id_diario`, `id_empresa`),
  CONSTRAINT `fk_libro_diario_empresas1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_diario_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_diario_moneda1`
    FOREIGN KEY (`id_moneda`)
    REFERENCES `moneda` (`id_moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_diario_documentos_sunat1`
    FOREIGN KEY (`id_tido`)
    REFERENCES `documentos_sunat` (`id_tido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_diario_cuentas_contables1`
    FOREIGN KEY (`id_cuenta_contable`)
    REFERENCES `cuentas_contables` (`id_cuenta_contable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_libro_diario_empresas1_idx` ON `libro_diario` (`id_empresa` ASC);

CREATE INDEX `fk_libro_diario_usuarios1_idx` ON `libro_diario` (`id_usuario` ASC);

CREATE INDEX `fk_libro_diario_moneda1_idx` ON `libro_diario` (`id_moneda` ASC);

CREATE INDEX `fk_libro_diario_documentos_sunat1_idx` ON `libro_diario` (`id_tido` ASC);

CREATE INDEX `fk_libro_diario_cuentas_contables1_idx` ON `libro_diario` (`id_cuenta_contable` ASC);


-- -----------------------------------------------------
-- Table `notas_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas_venta` (
  `id_ventas` INT NOT NULL,
  `periodo` INT(6) NOT NULL,
  `id_empresa` INT NOT NULL,
  `id_ventas_ref` INT NOT NULL,
  `periodo_ref` INT(6) NOT NULL,
  `id_empresa_ref` INT NOT NULL,
  CONSTRAINT `fk_notas_venta_ventas1`
    FOREIGN KEY (`id_ventas` , `periodo` , `id_empresa`)
    REFERENCES `ventas` (`id_ventas` , `periodo` , `id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_venta_ventas2`
    FOREIGN KEY (`id_ventas_ref` , `periodo_ref` , `id_empresa_ref`)
    REFERENCES `ventas` (`id_ventas` , `periodo` , `id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_notas_venta_ventas1_idx` ON `notas_venta` (`id_ventas` ASC, `periodo` ASC, `id_empresa` ASC);

CREATE INDEX `fk_notas_venta_ventas2_idx` ON `notas_venta` (`id_ventas_ref` ASC, `periodo_ref` ASC, `id_empresa_ref` ASC);


-- -----------------------------------------------------
-- Table `notas_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas_compras` (
  `id_compras` INT NOT NULL,
  `periodo` INT(6) NOT NULL,
  `id_empresa` INT NOT NULL,
  `id_compras_ref` INT NOT NULL,
  `periodo_ref` INT(6) NOT NULL,
  `id_empresa_ref` INT NOT NULL,
  PRIMARY KEY (`id_compras`, `periodo`, `id_empresa`, `id_compras_ref`, `periodo_ref`, `id_empresa_ref`),
  CONSTRAINT `fk_compras_compras_compras1`
    FOREIGN KEY (`id_compras` , `periodo` , `id_empresa`)
    REFERENCES `compras` (`id_compras` , `periodo` , `id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_compras_compras2`
    FOREIGN KEY (`id_compras_ref` , `periodo_ref` , `id_empresa_ref`)
    REFERENCES `compras` (`id_compras` , `periodo` , `id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_compras_compras_compras2_idx` ON `notas_compras` (`id_compras_ref` ASC, `periodo_ref` ASC, `id_empresa_ref` ASC);

CREATE INDEX `fk_compras_compras_compras1_idx` ON `notas_compras` (`id_compras` ASC, `periodo` ASC, `id_empresa` ASC);


-- -----------------------------------------------------
-- Table `ventas_libro_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_libro_diario` (
  `id_ventas` INT NOT NULL,
  `periodo` INT(6) NOT NULL,
  `id_empresa` INT NOT NULL,
  `periodo_diario` VARCHAR(6) NOT NULL,
  `id_diario` INT NOT NULL,
  `id_empresa_diario` INT NOT NULL,
  `subdiario` INT NOT NULL,
  PRIMARY KEY (`id_ventas`, `periodo`, `id_empresa`, `periodo_diario`, `id_diario`, `id_empresa_diario`, `subdiario`),
  CONSTRAINT `fk_ventas_libro_diario_ventas1`
    FOREIGN KEY (`id_ventas` , `periodo` , `id_empresa`)
    REFERENCES `ventas` (`id_ventas` , `periodo` , `id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_libro_diario_libro_diario1`
    FOREIGN KEY (`periodo_diario` , `id_diario` , `id_empresa_diario` , `subdiario`)
    REFERENCES `libro_diario` (`periodo` , `id_diario` , `id_empresa` , `subdiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ventas_libro_diario_libro_diario1_idx` ON `ventas_libro_diario` (`periodo_diario` ASC, `id_diario` ASC, `id_empresa_diario` ASC, `subdiario` ASC);

CREATE INDEX `fk_ventas_libro_diario_ventas1_idx` ON `ventas_libro_diario` (`id_ventas` ASC, `periodo` ASC, `id_empresa` ASC);


-- -----------------------------------------------------
-- Table `compras_libro_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras_libro_diario` (
  `id_compras` INT NOT NULL,
  `periodo` INT(6) NOT NULL,
  `id_empresa` INT NOT NULL,
  `periodo_diario` VARCHAR(6) NOT NULL,
  `id_diario` INT NOT NULL,
  `id_empresa_diario` INT NOT NULL,
  `subdiario` INT NOT NULL,
  PRIMARY KEY (`id_compras`, `periodo`, `id_empresa`, `periodo_diario`, `id_diario`, `id_empresa_diario`, `subdiario`),
  CONSTRAINT `fk_compras_libro_diario_compras1`
    FOREIGN KEY (`id_compras` , `periodo` , `id_empresa`)
    REFERENCES `compras` (`id_compras` , `periodo` , `id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_libro_diario_libro_diario1`
    FOREIGN KEY (`periodo_diario` , `id_diario` , `id_empresa_diario` , `subdiario`)
    REFERENCES `libro_diario` (`periodo` , `id_diario` , `id_empresa` , `subdiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_compras_libro_diario_libro_diario1_idx` ON `compras_libro_diario` (`periodo_diario` ASC, `id_diario` ASC, `id_empresa_diario` ASC, `subdiario` ASC);

CREATE INDEX `fk_compras_libro_diario_compras1_idx` ON `compras_libro_diario` (`id_compras` ASC, `periodo` ASC, `id_empresa` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `documentos_sunat`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `documentos_sunat` (`id_tido`, `nombre`, `abreviatura`, `cod_sunat`) VALUES (1, 'FACTURA', 'FT', '01');
INSERT INTO `documentos_sunat` (`id_tido`, `nombre`, `abreviatura`, `cod_sunat`) VALUES (2, 'RECIBO POR HONORARIOS', 'RH', '02');
INSERT INTO `documentos_sunat` (`id_tido`, `nombre`, `abreviatura`, `cod_sunat`) VALUES (3, 'BOLETA ', 'BL', '03');

COMMIT;


-- -----------------------------------------------------
-- Data for table `moneda`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `moneda` (`id_moneda`, `nombre`, `abreviatura`) VALUES (1, 'SOLES', 'S/');
INSERT INTO `moneda` (`id_moneda`, `nombre`, `abreviatura`) VALUES (2, 'DOLAR AMERICANO', 'US$');

COMMIT;

