/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.cl_compra;
import clases.cl_conectar;
import clases.cl_documentos_sunat;
import clases.cl_entidad;
import clases.cl_moneda;
import clases.cl_nota_compra;
import clases.cl_plan_contable;
import clases.cl_varios;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import static forms.frm_reg_venta.origen;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import minicontador.frm_menu;
import models.m_cuentas;
import models.m_documentos_sunat;
import models.m_moneda;
import objects.o_combobox;
import vistas.frm_ver_compras;
import vistas.frm_ver_ventas;

/**
 *
 * @author CALIDAD
 */
public class frm_reg_compra extends javax.swing.JDialog {

    cl_varios c_varios = new cl_varios();
    cl_conectar c_conectar = new cl_conectar();

    cl_entidad c_entidad = new cl_entidad();
    cl_compra c_compra = new cl_compra();
    cl_compra c_validarcompra = new cl_compra();
    cl_compra c_referencia = new cl_compra();
    cl_nota_compra c_nota = new cl_nota_compra();

    cl_documentos_sunat c_tido = new cl_documentos_sunat();
    cl_moneda c_moneda = new cl_moneda();

    m_documentos_sunat m_documentos = new m_documentos_sunat();
    m_moneda m_moneda = new m_moneda();
    m_cuentas m_cuentas = new m_cuentas();

    int id_usuario = frm_menu.c_usuario.getId_usuario();
    int id_empresa = frm_menu.c_empresa.getId_empresa();

    cl_plan_contable c_plan_contable = new cl_plan_contable();

    TextAutoCompleter tac_entidades = null;

    /**
     * Creates new form frm_reg_compra
     */
    public frm_reg_compra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        txt_fec_emision.setText(c_varios.formato_fecha_vista(c_varios.getFechaActual()));

        m_documentos.listar_combobox(cbx_tido);

        m_moneda.listar_monedas(cbx_moneda);

        m_cuentas.cbx_cuentas_orden(jComboBox1, "6");
    }

    private void verDocumentos() {
        String proveedor = txt_proveedor.getText();
        String query = "SELECT c.id_compras, c.periodo, c.fecha_emision, ds.cod_sunat, ds.abreviatura "
                + "AS doc_compra, c.serie, c.numero, en.documento AS doc_cliente, "
                + "en.nombre AS nombre_cliente, m.abreviatura AS moneda, c.tc, c.tipo_compra, c.subtotal, c.igv, c.total "
                + "FROM compras AS c "
                + "INNER JOIN entidad AS en ON en.id_entidad = c.id_entidad AND en.id_usuario = c.id_usuario "
                + "INNER JOIN documentos_sunat AS ds ON c.id_tido = ds.id_tido "
                + "INNER JOIN moneda AS m ON m.id_moneda = c.id_moneda "
                + "where en.documento= '" + proveedor + "' and c.id_empresa = '" + id_empresa + "' "
                + "order by c.fecha_emision asc, c.numero asc";
        jd_documentos.setModal(true);
        jd_documentos.setSize(850, 380);
        jd_documentos.setLocationRelativeTo(null);
        c_compra.ver_compras(t_documentos, query);
        jd_documentos.setVisible(true);
    }

    private void cargar_proveedores() {
        try {
            if (tac_entidades != null) {
                tac_entidades.removeAllItems();
            }
            tac_entidades = new TextAutoCompleter(txt_proveedor);

            tac_entidades.setMode(0);
            tac_entidades.setCaseSensitive(false);
            Statement st = c_conectar.conexion();
            String sql = "select documento from entidad where id_usuario = '" + id_usuario + "'";
            ResultSet rs = c_conectar.consulta(st, sql);
            while (rs.next()) {
                tac_entidades.addItem(rs.getString("documento"));
            }
            c_conectar.cerrar(rs);
            c_conectar.cerrar(st);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getLocalizedMessage());
            System.out.println(e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_documentos = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_documentos = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_seleccionar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_periodo = new javax.swing.JFormattedTextField();
        txt_fec_emision = new javax.swing.JFormattedTextField();
        txt_proveedor = new javax.swing.JTextField();
        txt_razon_social = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_fec_vcto = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbx_moneda = new javax.swing.JComboBox<>();
        txt_tc = new javax.swing.JFormattedTextField();
        txt_subtotal = new javax.swing.JTextField();
        txt_igv = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_serie = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        cbx_tido = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txt_referencia = new javax.swing.JTextField();
        btn_buscar_factura = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txt_fec_emision1 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_subtotal1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_subtotal2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_subtotal3 = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();

        t_documentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_documentos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(t_documentos);

        jLabel17.setText("Buscar:");

        btn_seleccionar.setText("Seleccionar");
        btn_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_documentosLayout = new javax.swing.GroupLayout(jd_documentos.getContentPane());
        jd_documentos.getContentPane().setLayout(jd_documentosLayout);
        jd_documentosLayout.setHorizontalGroup(
            jd_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_documentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addGroup(jd_documentosLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_seleccionar)))
                .addContainerGap())
        );
        jd_documentosLayout.setVerticalGroup(
            jd_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_documentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Documento de Compra");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Proveedor:");

        jLabel2.setText("Periodo:");

        jLabel3.setText("Fecha Emision");

        try {
            txt_periodo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_periodo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_periodoActionPerformed(evt);
            }
        });
        txt_periodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_periodoKeyPressed(evt);
            }
        });

        try {
            txt_fec_emision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_emision.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_emision.setEnabled(false);
        txt_fec_emision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_emisionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fec_emisionKeyReleased(evt);
            }
        });

        txt_proveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_proveedor.setEnabled(false);
        txt_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_proveedorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_proveedorKeyTyped(evt);
            }
        });

        txt_razon_social.setEnabled(false);

        jLabel4.setText("Moneda:");

        try {
            txt_fec_vcto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_vcto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_vcto.setEnabled(false);
        txt_fec_vcto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_vctoKeyPressed(evt);
            }
        });

        jLabel5.setText("Fecha Vcto:");

        jLabel6.setText("SubTotal:");

        jLabel7.setText("IGV:");

        jLabel8.setText("Total:");

        jLabel9.setText("Tipo Cambio:");

        cbx_moneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_moneda.setEnabled(false);
        cbx_moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_monedaActionPerformed(evt);
            }
        });
        cbx_moneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_monedaKeyPressed(evt);
            }
        });

        try {
            txt_tc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tc.setEnabled(false);
        txt_tc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tcKeyPressed(evt);
            }
        });

        txt_subtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subtotal.setEnabled(false);

        txt_igv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_igv.setEnabled(false);

        txt_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total.setEnabled(false);
        txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_totalKeyPressed(evt);
            }
        });

        jLabel10.setText("Tipo Documento:");

        jLabel11.setText("Serie / Numero:");

        txt_serie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serie.setEnabled(false);
        txt_serie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serieKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serieKeyTyped(evt);
            }
        });

        txt_numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_numero.setEnabled(false);
        txt_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_numeroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numeroKeyTyped(evt);
            }
        });

        cbx_tido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_tido.setEnabled(false);
        cbx_tido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_tidoKeyPressed(evt);
            }
        });

        jLabel13.setText("Cta. Cble.");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUENTA FINAL" }));
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });

        jLabel16.setText("Factura Amarre:");

        txt_referencia.setEnabled(false);

        btn_buscar_factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/find.png"))); // NOI18N
        btn_buscar_factura.setEnabled(false);
        btn_buscar_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_facturaActionPerformed(evt);
            }
        });

        jLabel18.setText("Fecha Contabilizacion:");

        try {
            txt_fec_emision1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_emision1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_emision1.setEnabled(false);
        txt_fec_emision1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_emision1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fec_emision1KeyReleased(evt);
            }
        });

        jLabel12.setText("IGV");

        jRadioButton1.setText("10%");

        jRadioButton2.setText("18%");

        jLabel14.setText("jLabel14");

        jLabel15.setText("SubTotal:");

        txt_subtotal1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subtotal1.setEnabled(false);

        jLabel19.setText("SubTotal:");

        txt_subtotal2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subtotal2.setEnabled(false);

        jLabel20.setText("SubTotal:");

        txt_subtotal3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subtotal3.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_razon_social, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbx_tido, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbx_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jRadioButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton2))
                                        .addComponent(txt_total)
                                        .addComponent(txt_igv))
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_subtotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_subtotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_subtotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_referencia)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btn_buscar_factura))
                                            .addComponent(txt_tc))))))
                        .addGap(102, 102, 102))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fec_emision1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_fec_emision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fec_vcto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fec_emision1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fec_emision, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fec_vcto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_razon_social, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_tido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(btn_buscar_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_igv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_subtotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_subtotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_subtotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/application_edit.png"))); // NOI18N
        jButton2.setText("Modificar");
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cross.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        frm_ver_compras formulario = new frm_ver_compras();
        c_varios.llamar_ventana_ancha(formulario);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbx_monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_monedaActionPerformed
        //al hacer clic en soles tc igual a 1.000
    }//GEN-LAST:event_cbx_monedaActionPerformed

    private void txt_proveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_proveedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_proveedor.getText().length() == 11) {
                //validar si existe
                String ruc = txt_proveedor.getText().trim();

                c_entidad.setDocumento(ruc);
                c_entidad.setId_usuario(id_usuario);
                boolean existe = c_entidad.validar_documento();
                if (existe) {
                    c_entidad.obtener_datos();
                    txt_razon_social.setText(c_entidad.getNombre());

                    o_combobox co_tido = (o_combobox) cbx_tido.getSelectedItem();
                    int id_tido = co_tido.getId();
                    c_validarcompra.setId_empresa(id_empresa);
                    c_validarcompra.setId_proveedor(c_entidad.getId_entidad());
                    c_validarcompra.setId_tido(id_tido);
                    c_validarcompra.setSerie(txt_serie.getText().toUpperCase());
                    c_validarcompra.setNumero(Integer.parseInt(txt_numero.getText()));

                    if (c_validarcompra.validarDocumento()) {
                        JOptionPane.showMessageDialog(null, "ESTE DOCUMENTO YA FUE REGISTRADO EN EL PERIODO " + c_validarcompra.getPeriodo() + ", CON REGISTRO NRO" + c_validarcompra.getId_compra());
                    } else {

                        if (id_tido == 4 || id_tido == 5) {
                            btn_buscar_factura.setEnabled(true);
                            //llamar funcion ver comprobantes
                            verDocumentos();
                            txt_buscar.requestFocus();
                        } else {
                            cbx_moneda.setEnabled(true);
                            cbx_moneda.requestFocus();
                        }
                    }
                } else {
                    Frame f = JOptionPane.getRootFrame();
                    frm_reg_entidad dialog = new frm_reg_entidad(f, true);
                    frm_reg_entidad.txt_ruc.setText(ruc);
                    dialog.setLocationRelativeTo(null);
                    dialog.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_txt_proveedorKeyPressed

    private void txt_periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_periodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_periodoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c_compra.setFecha_emision(c_varios.formato_fecha_mysql(txt_fec_emision.getText()));
        c_compra.setFecha_vcto(c_varios.formato_fecha_mysql(txt_fec_vcto.getText()));
        c_compra.setId_compra(1);
        c_compra.setId_empresa(id_empresa);
        c_compra.setId_moneda(((o_combobox) cbx_moneda.getSelectedItem()).getId());
        c_compra.setId_proveedor(c_entidad.getId_entidad());
        c_compra.setId_tido(((o_combobox) cbx_tido.getSelectedItem()).getId());
        c_compra.setNumero(Integer.parseInt(txt_numero.getText()));
        c_compra.setPeriodo(Integer.parseInt(txt_periodo.getText()));
        c_compra.setSerie(txt_serie.getText().toUpperCase());
        c_compra.setSubtotal(Double.parseDouble(txt_subtotal.getText()));
        c_compra.setIgv(Double.parseDouble(txt_igv.getText()));
        c_compra.setTotal(Double.parseDouble(txt_total.getText()));
        if (c_compra.getId_tido() == 4 || c_compra.getId_tido() == 5) {
            if (c_compra.getIgv() > 0) {
                c_compra.setIgv(c_compra.getIgv() * -1);
            }
            if (c_compra.getSubtotal() > 0) {
                c_compra.setSubtotal(c_compra.getSubtotal() * -1);
            }
            if (c_compra.getTotal() > 0) {
                c_compra.setTotal(c_compra.getTotal() * -1);
            }
        }
        c_compra.setTc(Double.parseDouble(txt_tc.getText()));
        c_compra.setTipo_compra(jTextField1.getText());
        c_compra.setId_usuario(id_usuario);
        c_compra.obtener_id();
        c_compra.insertar();

        if (c_compra.getId_tido() == 4 || c_compra.getId_tido() == 5) {
            c_nota.setIdnota(c_compra.getId_compra());
            c_nota.setPeriodo_nota(c_compra.getPeriodo());
            c_nota.setEmpresa_nota(c_compra.getId_empresa());
            c_nota.insertar();
        }

        JOptionPane.showMessageDialog(null, "DOCUMENTO AGREGADO CORRECTAMENTE \nESTE DOCUMENTO HA GENERADO EL CODIGO: " + c_compra.getPeriodo() + c_compra.getId_compra());
        //this.dispose();
        //frm_ver_compras formulario = new frm_ver_compras();
        //c_varios.llamar_ventana_ancha(formulario);

        txt_fec_emision.requestFocus();
        jButton1.setEnabled(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_periodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_periodoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_periodo.getText().trim().length() == 6) {
                txt_fec_emision.setEnabled(true);
                txt_fec_emision.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_periodoKeyPressed

    private void cbx_tidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_tidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_serie.setEnabled(true);
            txt_serie.requestFocus();
            txt_serie.selectAll();
        }
    }//GEN-LAST:event_cbx_tidoKeyPressed

    private void txt_serieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serieKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_serie.getText().length() > 0) {
                txt_numero.setEnabled(true);
                txt_numero.requestFocus();
                txt_numero.selectAll();
            }
        }
    }//GEN-LAST:event_txt_serieKeyPressed

    private void txt_numeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_numero.getText().length() < 13) {
                txt_fec_vcto.setEnabled(true);
                txt_fec_vcto.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_numeroKeyPressed

    private void txt_fec_emisionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_emisionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec_emision.getText().length() == 10) {
                String fecha = c_varios.formato_fecha_mysql(txt_fec_emision.getText());
                String periodo = txt_periodo.getText();
                int periodo_ingresado = Integer.parseInt(periodo);
                int periodo_fecha = Integer.parseInt(c_varios.formato_periodo(fecha));

                if (periodo_fecha <= periodo_ingresado) {
                    txt_fec_vcto.setText(txt_fec_emision.getText());
                    cbx_tido.setEnabled(true);
                    cbx_tido.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "LA FECHA NO CORRESPONDE AL PERIODO INGRESADO");
                    txt_fec_emision.selectAll();
                    txt_fec_emision.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txt_fec_emisionKeyPressed

    private void txt_fec_vctoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_vctoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec_vcto.getText().length() == 10) {
                txt_proveedor.setEnabled(true);
                txt_proveedor.requestFocus();
                cargar_proveedores();
            }
        }
    }//GEN-LAST:event_txt_fec_vctoKeyPressed

    private void cbx_monedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_monedaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            o_combobox co_moneda = (o_combobox) cbx_moneda.getSelectedItem();
            int id_moneda = co_moneda.getId();
            if (id_moneda == 1) {
                txt_tc.setText("1.000");
                txt_tc.setEnabled(false);
                jTextField3.setEnabled(true);
                jTextField3.requestFocus();
            } else {
                txt_tc.setText("");
                txt_tc.setEnabled(true);
                txt_tc.requestFocus();
            }

        }
    }//GEN-LAST:event_cbx_monedaKeyPressed

    private void txt_totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txt_total.getText();
            if (c_varios.esDecimal(texto)) {
                double total = Double.parseDouble(texto);
                txt_subtotal.setText(c_varios.formato_numero(total / 1.18));
                txt_igv.setText(c_varios.formato_numero(total / 1.18 * 0.18));
                txt_total.setText(c_varios.formato_numero(total));
                //txt_igv.setEnabled(true);
                jButton1.setEnabled(true);
                jButton1.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "INGRESE UN NUMERO CORRECTO.");
                txt_total.selectAll();
                txt_total.requestFocus();
            }

        }
    }//GEN-LAST:event_txt_totalKeyPressed

    private void txt_fec_emisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_emisionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fec_emisionKeyReleased

    private void txt_tcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tcKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_tc.getText().length() > 0) {
                jTextField3.setEnabled(true);
                jTextField3.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_tcKeyPressed

    private void txt_numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroKeyTyped
        c_varios.limitar_caracteres(evt, txt_numero, 12);
        c_varios.solo_numeros(evt);
    }//GEN-LAST:event_txt_numeroKeyTyped

    private void txt_proveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_proveedorKeyTyped
        c_varios.limitar_caracteres(evt, txt_proveedor, 11);
        c_varios.solo_numeros(evt);
    }//GEN-LAST:event_txt_proveedorKeyTyped

    private void txt_serieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serieKeyTyped
        c_varios.limitar_caracteres(evt, txt_serie, 12);
    }//GEN-LAST:event_txt_serieKeyTyped

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int contaritems = jComboBox2.getItemCount();
            if (contaritems > 1) {
                o_combobox ocuenta = (o_combobox) jComboBox2.getSelectedItem();
                jTextField1.setText(ocuenta.getId() + "");
                jTextField1.setEnabled(true);
                jTextField1.requestFocus();
            } else {
                jTextField1.setEnabled(true);
                txt_total.setEnabled(true);
                txt_total.requestFocus();
            }

        }
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void btn_buscar_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_facturaActionPerformed
        verDocumentos();
    }//GEN-LAST:event_btn_buscar_facturaActionPerformed

    private void btn_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarActionPerformed
        int fila_seleccionada = t_documentos.getSelectedRow();
        if (fila_seleccionada > -1) {
            c_referencia.setPeriodo(Integer.parseInt(t_documentos.getValueAt(fila_seleccionada, 9).toString()));
            c_referencia.setId_compra(Integer.parseInt(t_documentos.getValueAt(fila_seleccionada, 10).toString()));
            c_referencia.setId_empresa(id_empresa);
            if (c_referencia.obtener_datos()) {
                //enviar datos para registro de notas
                c_nota.setIdcompra(c_referencia.getId_compra());
                c_nota.setPeriodo_compra(c_referencia.getPeriodo());
                c_nota.setEmpresa_compra(c_referencia.getId_empresa());
                //obtener abreviatura de tipo de documento
                c_tido.setId_tido(c_referencia.getId_tido());
                c_tido.obtener_datos();
                //cargar datos en el formulario reg venta
                txt_referencia.setText(c_tido.getAbreviado() + " | " + c_referencia.getSerie() + " - " + c_referencia.getNumero());
                //obtener datos d emoneda
                c_moneda.setId_moneda(c_referencia.getId_moneda());
                c_moneda.obtener_datos();
                cbx_moneda.setSelectedItem(c_moneda.getNombre());

                int id_tido = ((o_combobox) cbx_tido.getSelectedItem()).getId();

                if (id_tido == 4) {
                    txt_subtotal.setText((c_referencia.getSubtotal() * -1) + "");
                    txt_igv.setText((c_referencia.getIgv() * -1) + "");
                    txt_total.setText((c_referencia.getTotal() * -1) + "");
                    txt_tc.setText((c_referencia.getTc()) + "");
                }
                jd_documentos.dispose();
                cbx_moneda.setEnabled(true);
                cbx_moneda.requestFocus();
            }
        }
    }//GEN-LAST:event_btn_seleccionarActionPerformed

    private void txt_fec_emision1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_emision1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fec_emision1KeyPressed

    private void txt_fec_emision1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_emision1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fec_emision1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_reg_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_reg_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_reg_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_reg_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_reg_compra dialog = new frm_reg_compra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_factura;
    private javax.swing.JButton btn_seleccionar;
    private javax.swing.JComboBox<String> cbx_moneda;
    private javax.swing.JComboBox<String> cbx_tido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_documentos;
    private javax.swing.JTable t_documentos;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JFormattedTextField txt_fec_emision;
    private javax.swing.JFormattedTextField txt_fec_emision1;
    private javax.swing.JFormattedTextField txt_fec_vcto;
    private javax.swing.JTextField txt_igv;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JFormattedTextField txt_periodo;
    private javax.swing.JTextField txt_proveedor;
    private javax.swing.JTextField txt_razon_social;
    private javax.swing.JTextField txt_referencia;
    private javax.swing.JTextField txt_serie;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_subtotal1;
    private javax.swing.JTextField txt_subtotal2;
    private javax.swing.JTextField txt_subtotal3;
    private javax.swing.JFormattedTextField txt_tc;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
