/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.cl_diario_venta;
import clases.cl_documentos_sunat;
import clases.cl_entidad;
import clases.cl_libro_diario;
import clases.cl_moneda;
import clases.cl_nota_venta;
import clases.cl_plan_contable;
import clases.cl_varios;
import clases.cl_venta;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import minicontador.frm_menu;
import models.m_cuentas;
import models.m_documentos_sunat;
import models.m_moneda;
import objects.o_combobox;
import vistas.frm_ver_ventas;

/**
 *
 * @author CALIDAD
 */
public class frm_reg_venta extends javax.swing.JDialog {
    
    cl_varios c_varios = new cl_varios();
    
    cl_entidad c_entidad = new cl_entidad();
    cl_venta c_venta = new cl_venta();
    cl_nota_venta c_nota = new cl_nota_venta();
    cl_libro_diario c_libro = new cl_libro_diario();
    cl_diario_venta c_diario = new cl_diario_venta();
    
    cl_venta c_referencia = new cl_venta();
    cl_documentos_sunat c_tido = new cl_documentos_sunat();
    cl_moneda c_moneda = new cl_moneda();
    
    m_documentos_sunat m_documentos = new m_documentos_sunat();
    m_moneda m_moneda = new m_moneda();
    m_cuentas m_cuentas = new m_cuentas();
    cl_plan_contable c_plan_contable = new cl_plan_contable();
    
    int id_usuario = frm_menu.c_usuario.getId_usuario();
    int id_empresa = frm_menu.c_empresa.getId_empresa();
    public static String origen = "";
    
    int id_tido;

    /**
     * Creates new form frm_reg_venta
     */
    public frm_reg_venta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txt_fecha.setText(c_varios.formato_fecha_vista(c_varios.getFechaActual()));
        
        m_documentos.listar_combobox(cbx_tido);
        
        m_moneda.listar_monedas(cbx_moneda);
        m_cuentas.cbx_cuentas_final(jComboBox2, "7", 7);
        txt_fecha.setEnabled(true);
        txt_fecha.requestFocus();
        /*m_cuentas.cbx_ventas_70(cbx_cuentas_70);
        m_cuentas.cbx_ventas_12(cbx_cuentas_12);*/
    }
    
    private double obtenerPorcentajeGV() {
        double porcentaje = 0.18;
        if (jRadioButton2.isSelected()) {
            porcentaje = 0.18;
        }
        if (jRadioButton1.isSelected()) {
            porcentaje = 0.1;
        }
        return porcentaje;
    }
    
    private void obtenerDatosIniciales() {
        c_venta.obtener_datos();
        txt_fecha.setText(c_varios.formato_fecha_vista(c_venta.getFecha()));
        txt_serie.setText(c_venta.getSerie());
        txt_numero.setText(c_venta.getNumero()+ "");
        
        c_entidad.setId_entidad(c_venta.getId_cliente());
        c_entidad.setId_usuario(c_venta.getId_usuario());
        c_entidad.obtener_datos();
        
        txt_ruc.setText(c_entidad.getDocumento());
        txt_cliente.setText(c_entidad.getNombre());
        
        double total = c_venta.getTotal();
        double igv = c_venta.getIgv();
        double subtotal = c_venta.getSubtotal();
        double exonerado = total - igv - subtotal;
        
        txt_subtotal.setText(c_varios.formato_numero(subtotal));
        txt_total.setText(c_varios.formato_numero(total));
        
        txt_subtotal_final.setText(c_varios.formato_numero(subtotal));
        txt_igv_final.setText(c_varios.formato_numero(igv));
        txt_exonerado_final.setText(c_varios.formato_numero(exonerado));
        txt_total_final.setText(c_varios.formato_numero(total));
        
        // seleccionar porentaje de igv
        
        //seleccionar documento 
        
        
        //seleccionar cuenta 
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_documentos = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_documentos = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_seleccionar = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btn_grabar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbx_moneda = new javax.swing.JComboBox<>();
        txt_tc = new javax.swing.JFormattedTextField();
        txt_subtotal = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_periodo = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_ruc = new javax.swing.JTextField();
        btn_add_cliente = new javax.swing.JButton();
        txt_cliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbx_tido = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_serie = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_referencia = new javax.swing.JTextField();
        btn_buscar_factura = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_subtotal_final = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_igv_final = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_exonerado_final = new javax.swing.JTextField();
        Total = new javax.swing.JLabel();
        txt_total_final = new javax.swing.JTextField();

        t_documentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_documentos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(t_documentos);

        jLabel13.setText("Buscar:");

        btn_seleccionar.setText("Seleccionar");
        btn_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_documentosLayout = new javax.swing.GroupLayout(jd_documentos.getContentPane());
        jd_documentos.getContentPane().setLayout(jd_documentosLayout);
        jd_documentosLayout.setHorizontalGroup(
            jd_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_documentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addGroup(jd_documentosLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_seleccionar)))
                .addContainerGap())
        );
        jd_documentosLayout.setVerticalGroup(
            jd_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_documentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registrar Documento de Venta");

        btn_grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/accept.png"))); // NOI18N
        btn_grabar.setText("Guardar");
        btn_grabar.setEnabled(false);
        btn_grabar.setFocusable(false);
        btn_grabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_grabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grabarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_grabar);

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/application_edit.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setEnabled(false);
        btn_modificar.setFocusable(false);
        btn_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_modificar);
        jToolBar1.add(jSeparator1);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cross.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setFocusable(false);
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_salir);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Montos del Comprobante"));

        jLabel4.setText("Moneda:");

        jLabel7.setText("SUB TOTAL:");

        jLabel8.setText("Total:");

        jLabel9.setText("Tipo Cambio:");

        cbx_moneda.setEnabled(false);
        cbx_moneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_monedaKeyPressed(evt);
            }
        });

        try {
            txt_tc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tc.setEnabled(false);
        txt_tc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tcKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tcKeyReleased(evt);
            }
        });

        txt_subtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subtotal.setEnabled(false);
        txt_subtotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_subtotalKeyPressed(evt);
            }
        });

        txt_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total.setEnabled(false);
        txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_totalKeyPressed(evt);
            }
        });

        jLabel15.setText("Cta. Cble.");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUENTA FINAL" }));
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });

        jLabel5.setText("% del IGV");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("10%");
        jRadioButton1.setEnabled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("18%");
        jRadioButton2.setEnabled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbx_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9)
                                .addGap(17, 17, 17)
                                .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_subtotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_total)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Comprobante"));

        jLabel3.setText("Fecha Emision");

        try {
            txt_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fechaKeyPressed(evt);
            }
        });

        jLabel2.setText("Periodo:");

        try {
            txt_periodo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_periodo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_periodo.setEnabled(false);

        jLabel1.setText("Cliente:");

        txt_ruc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ruc.setEnabled(false);
        txt_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rucKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_rucKeyPressed(evt);
            }
        });

        btn_add_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btn_add_cliente.setText("Nuevo Cliente");
        btn_add_cliente.setEnabled(false);
        btn_add_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_clienteActionPerformed(evt);
            }
        });

        txt_cliente.setEnabled(false);

        jLabel10.setText("Tipo Documento:");

        cbx_tido.setEnabled(false);
        cbx_tido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_tidoKeyPressed(evt);
            }
        });

        jLabel11.setText("Serie / Numero:");

        txt_serie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serie.setEnabled(false);
        txt_serie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serieKeyPressed(evt);
            }
        });

        txt_numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_numero.setEnabled(false);
        txt_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numeroKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_numeroKeyPressed(evt);
            }
        });

        jLabel12.setText("Factura Amarre:");

        txt_referencia.setEnabled(false);

        btn_buscar_factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/find.png"))); // NOI18N
        btn_buscar_factura.setEnabled(false);
        btn_buscar_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_facturaActionPerformed(evt);
            }
        });

        jLabel16.setText("Llenar solo si selecciono Nota de Credito / Debito");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cliente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar_factura))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_tido, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Totales"));

        jLabel6.setText("SubTotal:");

        txt_subtotal_final.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subtotal_final.setEnabled(false);
        txt_subtotal_final.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_subtotal_finalKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_subtotal_finalKeyPressed(evt);
            }
        });

        jLabel17.setText("IGV");

        txt_igv_final.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_igv_final.setEnabled(false);
        txt_igv_final.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_igv_finalKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_igv_finalKeyPressed(evt);
            }
        });

        jLabel18.setText("Exonerado");

        txt_exonerado_final.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_exonerado_final.setEnabled(false);
        txt_exonerado_final.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_exonerado_finalKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_exonerado_finalKeyPressed(evt);
            }
        });

        Total.setText("Total:");

        txt_total_final.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total_final.setEnabled(false);
        txt_total_final.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_total_finalKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_total_finalKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_subtotal_final, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_igv_final, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_exonerado_final, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_final, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_subtotal_final, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_igv_final, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_exonerado_final, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total_final, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
        frm_ver_ventas formulario = new frm_ver_ventas();
        c_varios.llamar_ventana_ancha(formulario);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void cbx_tidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_tidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_serie.setEnabled(true);
            txt_serie.requestFocus();
        }
    }//GEN-LAST:event_cbx_tidoKeyPressed

    private void txt_serieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serieKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_serie.getText().length() > 0) {
                txt_numero.setEnabled(true);
                txt_numero.requestFocus();
                txt_numero.selectAll();
            }
        }
    }//GEN-LAST:event_txt_serieKeyPressed

    private void txt_numeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_numero.getText().length() > 0) {

                //validar que documento no se haya registrado
                c_venta.setId_empresa(id_empresa);
                o_combobox co_tido = (o_combobox) cbx_tido.getSelectedItem();
                id_tido = co_tido.getId();
                c_venta.setId_tido(id_tido);
                c_venta.setSerie(txt_serie.getText().trim());
                c_venta.setNumero(Integer.parseInt(txt_numero.getText()));
                
                if (!c_venta.validar_documento()) {
                    //si no esta registrado pasar a seleccionar moneda
                    //si selecciono nota de credito o debito escoger documento de referencia
                    if (id_tido == 4 || id_tido == 5) {
                        btn_buscar_factura.setEnabled(true);
                        //llamar funcion ver comprobantes
                        ver_comprobantes();
                        txt_buscar.requestFocus();
                    } else {
                        cbx_moneda.setEnabled(true);
                        cbx_moneda.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "ESTE DOCUMENTO YA ESTA REGISTRADO");
                    btn_salir.doClick();
                }
            }
        }
    }//GEN-LAST:event_txt_numeroKeyPressed

    private void txt_fechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fechaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fecha.getText().length() == 10) {
                if (origen.equals("doc_anulado")) {
                    btn_grabar.setEnabled(true);
                    btn_grabar.requestFocus();
                }
                if (origen.equals("doc_activo")) {
                    txt_ruc.setEnabled(true);
                    btn_add_cliente.setEnabled(true);
                    txt_ruc.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txt_fechaKeyPressed
    
    private void ver_comprobantes() {
        String cliente = txt_ruc.getText();
        String query = "select v.id_ventas, v.periodo, v.fecha_emision, v.id_tido, ds.abreviatura as doc_venta, v.serie, v.numero, en.documento as doc_cliente, en.nombre as nombre_cliente, m.abreviatura as moneda, v.tc, v.tipo_venta, v.subtotal, v.igv, v.total, v.estado "
                + "from ventas as v "
                + "inner join entidad as en on en.id_entidad = v.id_entidad and en.id_usuario = v.id_usuario "
                + "inner join documentos_sunat as ds on v.id_tido = ds.id_tido "
                + "inner join moneda as m on m.id_moneda = v.id_moneda "
                + "where en.documento = '" + cliente + "' and v.id_empresa = '" + id_empresa + "' "
                + "order by v.fecha_emision asc, v.numero asc";
        System.out.println(query);
        jd_documentos.setModal(true);
        jd_documentos.setSize(850, 380);
        jd_documentos.setLocationRelativeTo(null);
        c_venta.ver_ventas(t_documentos, query);
        jd_documentos.setVisible(true);
    }
    private void txt_rucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_ruc.getText().length() == 11 || txt_ruc.getText().length() == 8 || txt_ruc.getText().equals("0")) {
                //validar si existe
                String ruc = txt_ruc.getText().trim();
                
                c_entidad.setDocumento(ruc);
                c_entidad.setId_usuario(id_usuario);
                boolean existe = c_entidad.validar_documento();
                if (existe) {
                    c_entidad.obtener_datos();
                    txt_cliente.setText(c_entidad.getNombre());
                    
                    cbx_tido.setEnabled(true);
                    cbx_tido.requestFocus();
                } else {
                    Frame f = JOptionPane.getRootFrame();
                    frm_reg_entidad dialog = new frm_reg_entidad(f, true);
                    frm_reg_entidad.txt_ruc.setText(ruc);
                    dialog.setLocationRelativeTo(null);
                    dialog.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_txt_rucKeyPressed

    private void txt_tcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tcKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_tc.getText().length() == 5) {
                jRadioButton1.setEnabled(true);
                jRadioButton2.setEnabled(true);
                txt_total.setEnabled(true);
                txt_total.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_tcKeyPressed

    private void txt_subtotal_finalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_subtotal_finalKeyPressed

    }//GEN-LAST:event_txt_subtotal_finalKeyPressed

    private void txt_rucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucKeyTyped
        c_varios.limitar_caracteres(evt, txt_ruc, 11);
        c_varios.solo_numeros(evt);
    }//GEN-LAST:event_txt_rucKeyTyped

    private void txt_numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroKeyTyped
        c_varios.limitar_caracteres(evt, txt_numero, 12);
        c_varios.solo_numeros(evt);
    }//GEN-LAST:event_txt_numeroKeyTyped

    private void txt_subtotal_finalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_subtotal_finalKeyTyped
        c_varios.limitar_caracteres(evt, txt_subtotal_final, 10);
        c_varios.solo_precio(evt);
    }//GEN-LAST:event_txt_subtotal_finalKeyTyped

    private void txt_totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txt_total.getText();
            if (c_varios.esDecimal(texto)) {
                double porcentajeigv = obtenerPorcentajeGV();
                double valortotal = Double.parseDouble(texto);
                double valorigv = valortotal / (1 + porcentajeigv) * porcentajeigv;
                double subtotal = valortotal / (1 + porcentajeigv);
                double exonerado = valortotal - valorigv - subtotal;
                txt_subtotal.setText(c_varios.formato_numero(subtotal));
                txt_subtotal_final.setText(c_varios.formato_numero(subtotal));
                txt_igv_final.setText(c_varios.formato_numero(valorigv));
                txt_exonerado_final.setText(c_varios.formato_numero(exonerado));
                txt_total_final.setText(c_varios.formato_numero(valortotal));
                txt_subtotal.setEnabled(true);
                txt_subtotal.requestFocus(true);

                //jComboBox2.setEnabled(true);
                //jComboBox2.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "INGRESE UN NUMERO CORRECTO.");
                txt_total.selectAll();
                txt_total.requestFocus();
            }
            
        }
    }//GEN-LAST:event_txt_totalKeyPressed
    
    private void llenar_libro() {
        c_libro.setPeriodo(c_venta.getPeriodo());
        c_libro.setId_empresa(id_empresa);
        c_libro.setId_usuario(id_usuario);
        c_libro.obtener_subdiario();
        c_libro.setTipo_asiento("M5");
        c_libro.setId_ccosto("");
        c_libro.setId_moneda(c_venta.getId_moneda());
        c_libro.setDoc_entidad(txt_ruc.getText());
        c_libro.setId_tido(c_venta.getId_tido());
        c_libro.setSerie(c_venta.getSerie());
        c_libro.setNumero(c_venta.getNumero());
        c_libro.setFecha_cble(c_venta.getFecha());
        c_libro.setFecha_vcto(c_venta.getFecha());
        c_tido.setId_tido(c_venta.getId_tido());
        c_tido.obtener_datos();
        c_libro.setGlosa(txt_cliente.getText() + " _ " + c_tido.getAbreviado() + " _ " + c_libro.getSerie() + " - " + c_libro.getNumero());
        c_libro.setCod_libro("");
        c_libro.setEstado(1);

        //diario _venta
        c_diario.setId_empresa_venta(c_venta.getId_empresa());
        c_diario.setPeriodo_venta(c_venta.getPeriodo());
        c_diario.setId_venta(c_venta.getId_venta());
        
        c_diario.setPeriodo_diario(c_libro.getPeriodo());
        c_diario.setSubdiario(c_libro.getSubdiario());
        c_diario.setId_empresa_diario(c_libro.getId_empresa());

        //para cuenta en70
        // o_combobox o_cuenta70 = (o_combobox) cbx_cuentas_70.getSelectedItem();
        //  c_libro.setId_cuenta(o_cuenta70.getId() + "");
        c_libro.setDebe(0);
        c_libro.setHaber(c_venta.getSubtotal());
        c_libro.obtener_id();
        c_libro.insertar();

        //diario 1
        c_diario.setId_diario(c_libro.getId_diario());
        c_diario.insertar();

        //para cuenta en12
//        o_combobox o_cuenta12 = (o_combobox) cbx_cuentas_12.getSelectedItem();
        // c_libro.setId_cuenta(o_cuenta12.getId() + "");
        c_libro.setDebe(c_venta.getTotal());
        c_libro.setHaber(0);
        c_libro.obtener_id();
        c_libro.insertar();

        //diario 2
        c_diario.setId_diario(c_libro.getId_diario());
        c_diario.insertar();

        //para cuenta en40
        c_libro.setId_cuenta("40111");
        c_libro.setDebe(0);
        c_libro.setHaber(c_venta.getIgv());
        c_libro.obtener_id();
        c_libro.insertar();

        //diario 3
        c_diario.setId_diario(c_libro.getId_diario());
        c_diario.insertar();
    }
    
    private void insertarDiario() {
        c_libro.setPeriodo(c_venta.getPeriodo());
        c_libro.setId_empresa(id_empresa);
        c_libro.setId_usuario(id_usuario);
        c_libro.obtener_subdiario();
        c_libro.setTipo_asiento("M5");
        c_libro.setId_moneda(1);
        
        c_libro.setId_ccosto("");
        c_libro.setDoc_entidad(txt_ruc.getText());
        c_libro.setId_tido(c_venta.getId_tido());
        c_libro.setSerie(c_venta.getSerie());
        c_libro.setNumero(c_venta.getNumero());
        c_libro.setFecha_cble(c_venta.getFecha());
        c_libro.setFecha_vcto(c_libro.getFecha_cble());
        c_libro.setGlosa("VENTA");
        c_libro.setCod_libro("");
        c_libro.setEstado(1);
        c_libro.setId_cuenta("12");
        c_libro.setDebe(c_venta.getTotal() / 1.18);
        c_libro.setHaber(0);
        c_libro.obtener_id();
        c_libro.insertar();
    }

    private void btn_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grabarActionPerformed
        btn_grabar.setEnabled(false);
        
        c_venta.setId_empresa(id_empresa);
        c_venta.setFecha(c_varios.formato_fecha_mysql(txt_fecha.getText()));
        o_combobox co_tido = (o_combobox) cbx_tido.getSelectedItem();
        id_tido = co_tido.getId();
        c_venta.setId_tido(id_tido);
        c_venta.setSerie(txt_serie.getText().trim());
        c_venta.setNumero(Integer.parseInt(txt_numero.getText()));
        c_venta.setPeriodo(c_varios.formato_periodo(c_venta.getFecha()));
        c_venta.setTipo_venta(1);
        c_venta.setId_usuario(id_usuario);
        
        if (origen.equals("doc_anulado")) {
            c_venta.setId_cliente(0);
            c_venta.setId_moneda(1);
            c_venta.setTc(1.00);
            c_venta.setSubtotal(0);
            c_venta.setIgv(0);
            c_venta.setTotal(0);
            c_venta.setEstado(2);
            c_venta.obtener_id();
        }
        
        if (origen.equals("doc_activo")) {
            c_venta.setId_cliente(c_entidad.getId_entidad());
            
            o_combobox co_moneda = (o_combobox) cbx_moneda.getSelectedItem();
            int id_moneda = co_moneda.getId();
            c_venta.setId_moneda(id_moneda);
            c_venta.setTc(Double.parseDouble(txt_tc.getText()));
            c_venta.setSubtotal(Double.parseDouble(txt_subtotal_final.getText()));
            c_venta.setIgv(Double.parseDouble(txt_igv_final.getText()));
            c_venta.setTotal(Double.parseDouble(txt_total_final.getText()));
            /*if (id_tido == 4 || id_tido == 5) {
                c_venta.setSubtotal(c_venta.getSubtotal() * -1);
                c_venta.setIgv(c_venta.getIgv() * -1);
                c_venta.setTotal(c_venta.getTotal() * -1);
            }*/
            c_venta.setEstado(1);
            c_venta.obtener_id();
        }
        
        if (c_venta.insertar()) {
            insertarDiario();
            if (id_tido == 4 || id_tido == 5) {
                c_nota.setId_nota(c_venta.getId_venta());
                c_nota.setPeriodo_nota(c_venta.getPeriodo());
                c_nota.setId_empresa_nota(c_venta.getId_empresa());
                c_nota.insertar();
            }
            //llenar_libro();
            JOptionPane.showMessageDialog(null, "DOCUMENTO AGREGADO CORRECTAMENTE \nESTE DOCUMENTO GENERO EL CODIGO: " + c_venta.getPeriodo() + c_venta.getId_venta());

            /*
            this.dispose();
            frm_ver_ventas formulario = new frm_ver_ventas();
            c_varios.llamar_ventana_ancha(formulario);
             */
            limpiar();
            txt_fecha.requestFocus();
        }
    }//GEN-LAST:event_btn_grabarActionPerformed

    private void limpiar() {
        jLabel16.setText("ULTIMO DOCUMENTO AGREGADO "   + c_venta.getSerie() + " - " + c_venta.getNumero());
        txt_subtotal_final.setText("0");
        txt_igv_final.setText("0");
        txt_exonerado_final.setText("0");
        txt_total_final.setText("0");
        txt_total.setText("");
        txt_subtotal.setText("");
        txt_numero.setText("");
        txt_fecha.requestFocus();
    }
    
    private void btn_add_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_clienteActionPerformed

    private void btn_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarActionPerformed
        int fila_seleccionada = t_documentos.getSelectedRow();
        if (fila_seleccionada > -1) {
            c_referencia.setPeriodo(t_documentos.getValueAt(fila_seleccionada, 10).toString());
            c_referencia.setId_venta(Integer.parseInt(t_documentos.getValueAt(fila_seleccionada, 11).toString()));
            c_referencia.setId_empresa(id_empresa);
            if (c_referencia.obtener_datos()) {
                //enviar datos para registro de notas 
                c_nota.setId_venta(c_referencia.getId_venta());
                c_nota.setPeriodo_venta(c_referencia.getPeriodo());
                c_nota.setId_empresa_venta(c_referencia.getId_empresa());
                //obtener abreviatura de tipo de documento
                c_tido.setId_tido(c_referencia.getId_tido());
                c_tido.obtener_datos();
                //cargar datos en el formulario reg venta
                txt_referencia.setText(c_tido.getAbreviado() + " | " + c_referencia.getSerie() + " - " + c_referencia.getNumero());
                //obtener datos d emoneda
                c_moneda.setId_moneda(c_referencia.getId_moneda());
                c_moneda.obtener_datos();
                cbx_moneda.setSelectedItem(c_moneda.getNombre());
                if (id_tido == 4) {
                    txt_subtotal_final.setText((c_referencia.getSubtotal() * -1) + "");
                    txt_subtotal.setText((c_referencia.getIgv() * -1) + "");
                    txt_total.setText((c_referencia.getTotal() * -1) + "");
                    txt_tc.setText((c_referencia.getTc()) + "");
                }
                jd_documentos.dispose();
                cbx_moneda.setEnabled(true);
                cbx_moneda.requestFocus();
            }
        }
    }//GEN-LAST:event_btn_seleccionarActionPerformed

    private void btn_buscar_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_facturaActionPerformed
        ver_comprobantes();
    }//GEN-LAST:event_btn_buscar_facturaActionPerformed

    private void cbx_monedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_monedaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            o_combobox co_moneda = (o_combobox) cbx_moneda.getSelectedItem();
            int id_moneda = co_moneda.getId();
            if (id_moneda == 1) {
                txt_tc.setText("1.000");
                txt_tc.setEnabled(false);
                jRadioButton1.setEnabled(true);
                jRadioButton2.setEnabled(true);
                txt_total.setEnabled(true);
                txt_total.requestFocus();
            } else {
                txt_tc.setText("");
                txt_tc.setEnabled(true);
                txt_tc.requestFocus();
            }
            
        }
    }//GEN-LAST:event_cbx_monedaKeyPressed

    private void txt_tcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tcKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tcKeyReleased

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int contaritems = jComboBox2.getItemCount();
            if (contaritems > 1) {
                o_combobox ocuenta = (o_combobox) jComboBox2.getSelectedItem();
                btn_grabar.setEnabled(true);
                btn_grabar.requestFocus();
            } else {
                txt_total.setEnabled(true);
                txt_total.requestFocus();
            }
            
        }
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        txt_subtotal.requestFocus();

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txt_igv_finalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_igv_finalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_igv_finalKeyTyped

    private void txt_igv_finalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_igv_finalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_igv_finalKeyPressed

    private void txt_exonerado_finalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_exonerado_finalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_exonerado_finalKeyTyped

    private void txt_exonerado_finalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_exonerado_finalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_exonerado_finalKeyPressed

    private void txt_total_finalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_total_finalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_finalKeyTyped

    private void txt_total_finalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_total_finalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_finalKeyPressed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        txt_subtotal.requestFocus();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txt_subtotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_subtotalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txt_subtotal.getText();
            if (texto.length() > 0) {
                if (c_varios.esDecimal(texto)) {
                    double porcentajeigv = obtenerPorcentajeGV();
                    double subtotal = Double.parseDouble(texto);
                    double valortotal = Double.parseDouble(txt_total.getText());
                    double valorigv = subtotal * porcentajeigv;
                    
                    double exonerado = valortotal - valorigv - subtotal;
                    txt_subtotal.setText(c_varios.formato_numero(subtotal));
                    txt_subtotal_final.setText(c_varios.formato_numero(subtotal));
                    txt_igv_final.setText(c_varios.formato_numero(valorigv));
                    txt_exonerado_final.setText(c_varios.formato_numero(exonerado));
                    txt_total_final.setText(c_varios.formato_numero(valortotal));
                    jComboBox2.setEnabled(true);
                    jComboBox2.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "No ha ingresado un numero");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No ha ingresado un importe");
            }
        }
    }//GEN-LAST:event_txt_subtotalKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_reg_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_reg_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_reg_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_reg_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_reg_venta dialog = new frm_reg_venta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total;
    private javax.swing.JButton btn_add_cliente;
    private javax.swing.JButton btn_buscar_factura;
    private javax.swing.JButton btn_grabar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_seleccionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_moneda;
    private javax.swing.JComboBox<String> cbx_tido;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_documentos;
    private javax.swing.JTable t_documentos;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_exonerado_final;
    private javax.swing.JFormattedTextField txt_fecha;
    private javax.swing.JTextField txt_igv_final;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JFormattedTextField txt_periodo;
    private javax.swing.JTextField txt_referencia;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_serie;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_subtotal_final;
    private javax.swing.JFormattedTextField txt_tc;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_total_final;
    // End of variables declaration//GEN-END:variables
}
